language: node_js
node_js:
  - "11.0.0"

install:
  - npm install

script:
  - npm run test
  - npm run coverage
after_script:
  - COVERALLS_REPO_TOKEN=WsmZ3EJcRZuxuyKBCcG8MQgbnwo8ZXGK0 npm run coveralls
